### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by langston-barrett** [gbalats/souffle-mode#2]
The README mentions a LICENSE file, but there isn't one in the repo. Additionally, the `.el` files themselves refer to the GPL in their headers, but the README mentions the MIT license.

**Comment by gbalats** [comment]
Ah, apologies. MIT license was the intended one but this mode was copied in haste from another one I had. I will update it as soon as I find some time, unless you intend to send a pull request my way to do it faster.

**Comment by gbalats** [comment]
The LICENSE file as well as the license references of the `.el` files have all been updated to the MIT license.
